import assert from "node:assert/strict";
import { createTestEngine, IDS } from "./intellix-engine.mjs";
const results = [];
function test(phase, name, fn) { try { fn(); results.push({ phase, name, pass: true }); } catch (error) { results.push({ phase, name, pass: false, error }); } }
function expectCode(response, code) { assert.equal(response.success, false); assert.equal(response.code, code); }
function freshOpen() { const engine = createTestEngine(); engine.setTime("2026-09-11T12:00:00+05:30"); return engine; }
test("PHASE 6", "release states and leakage protection", () => { const e = createTestEngine(); assert.equal(e.getSelectionState(), "NOT_RELEASED"); assert.deepEqual(e.getProblems(IDS.agr).data.problems, []); e.setTime("2026-09-11T12:00:00+05:30"); assert.equal(e.getSelectionState(), "SELECTION_OPEN"); e.setTime("2026-09-11T19:00:00+05:30"); assert.equal(e.getSelectionState(), "SELECTION_CLOSED"); });
test("PHASE 6", "domain isolation and tampering", () => { const e = freshOpen(); assert.deepEqual(e.getProblems(IDS.agr, { domainId: "EDU", teamId: "BIT-AI-TEST-002" }).data.problems.map((p) => p.PSID), ["AGR-01", "AGR-02", "AGR-04"]); assert.deepEqual(e.getProblems(IDS.edu).data.problems.map((p) => p.PSID), ["EDU-01", "EDU-02"]); });
test("PHASE 6", "disabled and already-selected filtering", () => { const e = freshOpen(); e.lockProblem(IDS.agr2, { psid: "AGR-01" }); const ids = e.getProblems(IDS.agr).data.problems.map((p) => p.PSID); assert.deepEqual(ids, ["AGR-02", "AGR-04"]); assert(!ids.includes("AGR-03")); });
test("PHASE 7", "lock validation and success", () => { const e = freshOpen(); assert.equal(e.lockProblem(IDS.agr, { psid: "AGR-01" }).success, true); assert.equal(e.state().selections.length, 1); expectCode(e.lockProblem(IDS.agr, { psid: "AGR-02" }), "TEAM_ALREADY_LOCKED"); expectCode(e.lockProblem(IDS.agr2, { psid: "AGR-01" }), "PROBLEM_ALREADY_LOCKED"); expectCode(e.lockProblem(IDS.edu, { psid: "AGR-02" }), "WRONG_DOMAIN"); expectCode(e.lockProblem(IDS.agr2, { psid: "AGR-03" }), "PROBLEM_DISABLED"); });
test("PHASE 7", "closed, duplicate, and idempotent requests", () => { const e = freshOpen(); assert.equal(e.lockProblem(IDS.agr, { psid: "AGR-02" }).success, true); expectCode(e.lockProblem(IDS.agr, { psid: "AGR-02" }), "TEAM_ALREADY_LOCKED"); assert.equal(e.state().selections.length, 1); e.closeSelection(IDS.admin); expectCode(e.lockProblem(IDS.agr2, { psid: "AGR-04" }), "SELECTION_CLOSED"); });
test("PHASE 7", "concurrent locking preserves one-owner invariant", () => { const e = freshOpen(); const responses = [e.lockProblem(IDS.agr, { psid: "AGR-04" }), e.lockProblem(IDS.agr2, { psid: "AGR-04" })]; assert.equal(responses.filter((r) => r.success).length, 1); assert.equal(responses.filter((r) => r.code === "PROBLEM_ALREADY_LOCKED").length, 1); assert.equal(e.state().selections.filter((s) => s.psid === "AGR-04").length, 1); });
test("PHASE 8", "admin auth and participant rejection", () => { const e = createTestEngine(); expectCode(e.adminTeams(IDS.student), "ADMIN_REQUIRED"); expectCode(e.adminTeams(IDS.outsider), "ADMIN_REQUIRED"); expectCode(e.adminTeams(IDS.invalid), "ADMIN_REQUIRED"); expectCode(e.adminTeams(IDS.agr), "ADMIN_REQUIRED"); });
test("PHASE 8", "admin CRUD persists after refresh", () => { const e = createTestEngine(); e.addTeam(IDS.admin, { teamId: "BIT-AI-TEST-004", teamName: "New Synthetic Team", leaderEmail: "new.test@bitsathy.ac.in", domainId: "AGR" }); e.updateTeam(IDS.admin, { teamId: "BIT-AI-TEST-004", teamName: "Updated Synthetic Team" }); e.addProblem(IDS.admin, { psid: "AGR-99", domainId: "AGR", title: "Synthetic 99", description: "Synthetic description", whatToBuild: "Synthetic build" }); e.updateProblem(IDS.admin, { psid: "AGR-99", title: "Updated Synthetic 99" }); e.updateProblem(IDS.admin, { psid: "AGR-99", status: "DISABLED" }); assert.equal(e.adminTeams(IDS.admin, "Updated Synthetic").data[0].teamName, "Updated Synthetic Team"); assert.equal(e.adminProblems(IDS.admin, { query: "AGR-99" }).data[0].status, "DISABLED"); });
test("PHASE 8", "domain and configuration validation", () => { const e = freshOpen(); assert.equal(e.updateDomain(IDS.admin, { domainId: "AGR", maximumTeams: 40, status: "ACTIVE" }).success, true); expectCode(e.updateDomain(IDS.admin, { domainId: "AGR", maximumTeams: -1 }), "CAPACITY_BELOW_USAGE"); expectCode(e.updateConfig(IDS.admin, { problemReleaseDateTime: "2026-09-12T00:00:00Z", problemCloseDateTime: "2026-09-11T00:00:00Z" }), "INVALID_CONFIGURATION"); e.closeSelection(IDS.admin); assert.equal(e.getSelectionState(), "SELECTION_CLOSED"); });
test("PHASE 8", "release now and configuration persistence", () => { const e = createTestEngine(); assert.equal(e.releaseNow(IDS.admin).data.selectionState, "SELECTION_OPEN"); assert.equal(e.getProblems(IDS.agr).data.problems.length, 3); const release = "2026-09-11T11:00:00+05:30"; const close = "2026-09-11T20:00:00+05:30"; assert.equal(e.updateConfig(IDS.admin, { problemReleaseDateTime: release, problemCloseDateTime: close }).success, true); assert.equal(e.getAdminConfiguration(IDS.admin).data.problemReleaseDateTime, release); assert.equal(e.getAdminStats(IDS.admin).success, true); });

// --- PHASE 9: Selection reset ---
test("PHASE 9", "ALLOW_SELECTION_RESET defaults to FALSE, blocks reset", () => { const e = freshOpen(); e.lockProblem(IDS.agr, { psid: "AGR-01" }); expectCode(e.removeTeamSelection(IDS.admin, "BIT-AI-TEST-001"), "RESET_NOT_ALLOWED"); expectCode(e.removeAllSelections(IDS.admin), "RESET_NOT_ALLOWED"); assert.equal(e.state().selections.length, 1, "selection must remain"); });
test("PHASE 9", "participant cannot call reset ops", () => { const e = freshOpen(); e.setAllowReset(IDS.admin, "TRUE"); e.lockProblem(IDS.agr, { psid: "AGR-01" }); expectCode(e.removeTeamSelection(IDS.agr, "BIT-AI-TEST-001"), "ADMIN_REQUIRED"); expectCode(e.removeAllSelections(IDS.agr), "ADMIN_REQUIRED"); assert.equal(e.state().selections.length, 1, "selection must survive participant attempt"); });
test("PHASE 9", "setAllowReset toggle: TRUE enables, FALSE re-disables", () => { const e = createTestEngine(); const r1 = e.setAllowReset(IDS.admin, "TRUE"); assert.equal(r1.data.allowSelectionReset, true); assert.equal(e.getAdminConfiguration(IDS.admin).data.allowSelectionReset, true); const r2 = e.setAllowReset(IDS.admin, "FALSE"); assert.equal(r2.data.allowSelectionReset, false); assert.equal(e.getAdminConfiguration(IDS.admin).data.allowSelectionReset, false); });
test("PHASE 9", "removeTeamSelection: removes one team's lock, problem becomes available again", () => { const e = freshOpen(); e.setAllowReset(IDS.admin, "TRUE"); e.lockProblem(IDS.agr, { psid: "AGR-01" }); e.lockProblem(IDS.agr2, { psid: "AGR-02" }); assert.equal(e.state().selections.length, 2); const r = e.removeTeamSelection(IDS.admin, "BIT-AI-TEST-001"); assert.equal(r.success, true); assert.equal(r.data.removed, 1); assert.equal(e.state().selections.length, 1, "one selection must remain"); const problems = e.getProblems(IDS.agr).data.problems; assert.ok(problems.some((p) => p.PSID === "AGR-01"), "AGR-01 must be available again"); assert.ok(!problems.some((p) => p.PSID === "AGR-02"), "AGR-02 still locked by agr2 must stay hidden"); });
test("PHASE 9", "removeTeamSelection: team not found returns TEAM_NOT_FOUND", () => { const e = freshOpen(); e.setAllowReset(IDS.admin, "TRUE"); expectCode(e.removeTeamSelection(IDS.admin, "BIT-AI-GHOST-999"), "TEAM_NOT_FOUND"); });
test("PHASE 9", "removeTeamSelection on team with no selection: returns removed=0", () => { const e = freshOpen(); e.setAllowReset(IDS.admin, "TRUE"); const r = e.removeTeamSelection(IDS.admin, "BIT-AI-TEST-001"); assert.equal(r.success, true); assert.equal(r.data.removed, 0); });
test("PHASE 9", "removeAllSelections: clears all locks, teams and problems intact", () => { const e = freshOpen(); e.setAllowReset(IDS.admin, "TRUE"); e.lockProblem(IDS.agr, { psid: "AGR-01" }); e.lockProblem(IDS.agr2, { psid: "AGR-02" }); e.lockProblem(IDS.edu, { psid: "EDU-01" }); assert.equal(e.state().selections.length, 3); const r = e.removeAllSelections(IDS.admin); assert.equal(r.success, true); assert.equal(r.data.removed, 3); assert.equal(e.state().selections.length, 0); assert.equal(e.state().teams.length, 3, "team count must be unchanged"); assert.equal(e.state().problems.length, 7, "problem count must be unchanged"); const agrProblems = e.getProblems(IDS.agr).data.problems; assert.ok(agrProblems.some((p) => p.PSID === "AGR-01"), "AGR-01 must be available again"); assert.ok(agrProblems.some((p) => p.PSID === "AGR-02"), "AGR-02 must be available again"); });
test("PHASE 9", "removeSelectionByPsid: removes corrupt selection by PSID without requiring TeamID", () => {
  const e = freshOpen();
  e.setAllowReset(IDS.admin, "TRUE");
  // Inject synthetic corrupt selection record (TeamID undefined)
  e.state().selections.push({ teamId: "undefined", domainId: "EDU", psid: "EDU-01", status: "LOCKED", selectedAt: "2026-09-12T00:00:00Z" });
  assert.ok(e.state().selections.some((s) => s.psid === "EDU-01"), "Corrupt selection present");
  const r = e.removeSelectionByPsid(IDS.admin, "EDU-01");
  assert.equal(r.success, true);
  assert.equal(r.data.removed, 1);
  assert.ok(!e.state().selections.some((s) => s.psid === "EDU-01"), "Corrupt selection removed");
});

const failed = results.filter((result) => !result.pass);
for (const phase of ["PHASE 6", "PHASE 7", "PHASE 8", "PHASE 9"]) {
  const phaseResults = results.filter((result) => result.phase === phase);
  console.log(`${phase}\n${phaseResults.filter((r) => r.pass).length}/${phaseResults.length} PASSED`);
  for (const result of phaseResults.filter((r) => !r.pass)) console.log(`FAIL ${result.name}\nEXPECTED: test invariant\nACTUAL: ${result.error.message}\nROOT CAUSE: ${result.error.stack?.split("\n")[1]?.trim() || "unknown"}`);
}
console.log(`\nJSON TEST HARNESS: ${failed.length ? "FAIL" : "PASS"}`);
console.log(`CONCURRENCY: ${results.find((r) => r.name.includes("concurrent"))?.pass ? "PASS" : "FAIL"}`);
console.log(`IDEMPOTENCY: ${results.find((r) => r.name.includes("idempotent"))?.pass ? "PASS" : "FAIL"}`);
console.log(`ADMIN CRUD: ${results.find((r) => r.name.includes("admin CRUD"))?.pass ? "PASS" : "FAIL"}`);
console.log(`SELECTION RESET: ${results.filter((r) => r.phase === "PHASE 9").every((r) => r.pass) ? "PASS" : "FAIL"}`);
if (failed.length) process.exitCode = 1;